#!/bin/sh

dist="../../versions/3.2/bin"

set +e
rm -rf tmp
mkdir tmp
set -e

pushd tmp

wget http://download.redis.io/releases/redis-3.2.0.tar.gz
tar xzf redis-3.2.0.tar.gz
cd redis-3.2.0
make

mkdir -p $dist
cp -f src/redis-cli $dist
cp -f src/redis-server $dist

popd
rm -rf tmp
